### ISSUE TITLE
How do I revert to the last commit I have without messing anyone else up?

### ISSUE THREAD

**Issue by timhilton** [timhilton/RoadTripRouletteApplication#13]
I don't want to reset anyone else's work.  But I made some changes that I want to undo on my machine and that means going back to the last pull I made.  I'm not sure how to do that.

**Comment by rapala61** [comment]
did you push to origin AFTER the last pull you made, in other words, are the undesired changes already pushed to everyone? or they just exist in you localhost?

**Comment by timhilton** [comment]
they were just local host.  git checkout -f fixed it.  Thanks!

**Comment by rapala61** [comment]
OK cool, the takeaway is, as long as you have not pushed the code to the cloud, you are still safe to nuke your local repo, just try not to :+1: .
