### ISSUE TITLE
Need Help With Yelp API

### ISSUE THREAD

**Issue by timhilton** [timhilton/RoadTripRouletteApplication#19]
Can't seem to get it to return different results...

**Comment by rapala61** [comment]
Hey, post the different urls you are using to get the different results

**Comment by timhilton** [comment]
I was using the ruby gem and trying it out in a tester rails app per the documentation on the yelp site and going off of the github code.  I'm not sure I set it up right.  It's very confusing.

**Comment by rapala61** [comment]
are you able to send a request? did you follow this steps? where any "YOUR_" string means you need to change this values with the right ones (did you get all of these keys from yelp?)
```ruby
require 'yelp'

Yelp.client.configure do |config|
  config.consumer_key = YOUR_CONSUMER_KEY
  config.consumer_secret = YOUR_CONSUMER_SECRET
  config.token = YOUR_TOKEN
  config.token_secret = YOUR_TOKEN_SECRET
end

Yelp.client.search('San Francisco', { term: 'food' })
```

**Comment by timhilton** [comment]
Yes, all of that is good.  The problem is when I send a request, no matter what the request is, it returns the same 16 things.

**Comment by emilylordahl** [comment]
Resolved with Rafa in person!

**Comment by timhilton** [comment]
Thank you Rafa!  The absolute man!!!
